package nickNetology

data class Post(
    var id: Int = 0,
    val ownerId: Int = 0,
    val fromId: Int = 0,
    val createdBy: Int = 0,
    val date: Int = 0,
    val text: String? = null,
    val replyOwnerId: Int = 0,
    val replyPostId: Int = 0,
    val friendsOnly: Boolean = true,
    val comments: Any? = null,
    val copyright: String? = null,
    val likes: Likes? = Likes(),
    val reposts: Reposts? = Reposts(),
    val views: Any? = null,
    val postType: String? = null,
    val postSourse: Any? = null,
    val geo: Any?=null,
    val signerId: Int? = null,
    val copyHistory: Array<Post>? = null,
    val canPin: Boolean = false,
    val canDelete: Boolean = false,
    val canEdit: Boolean = false,
    val isPinned: Boolean? = null,
    val markedAsAds: Boolean = false,
    val isFavorite: Boolean = false,
    val postponedId: Int? = null,
    val original: Post? = null
)
